require "user.plugins.packer"
require "user.plugins.jaq"
require "user.plugins.alpha"
require "user.plugins.gitsigns"
require "user.plugins.cmp"
require "user.plugins.icons"
require "user.plugins.treesitter"
require "user.plugins.comment"
require "user.plugins.autopairs"
-- require "user.plugins.lualine"
require "user.plugins.lualine-simple"
require "user.plugins.bufferline"
require "user.plugins.nvim-tree"
require "user.plugins.whichkey"
-- require "user.plugins.indent-blankline"
require "user.plugins.toggleterm"
require "user.plugins.telescope"
require "user.plugins.colorizer"
require "user.plugins.illuminate"
require "user.plugins.lsp"
